// User, Event, and Ticket model types are auto-generated by Prisma
// (see src/generated/prisma) — no need to hand-maintain them here.

export interface AuthResponse {
  token: string;
}

export interface AuthPayload {
  userId: string;
  email?: string;
}

export interface ApiResponse<T> {
  data?: T;
  error?: string;
  message?: string;
}
